version: '3.7'
services:

  # https://github.com/tiredofit/docker-fusiondirectory#configuration
  fusiondirectory:
    container_name: fusiondirectory
    image: tiredofit/fusiondirectory:1.4
    labels:
      caddy: fusiondirectory.example.org
      caddy.reverse_proxy: '{{upstreams}}'
      caddy_fd: fd.example.org
      caddy_fd.redir: 'https://fusiondirectory.example.org{uri} permanent'
    volumes:
    - fusiondirectory_logs:/www/logs
    # - fusiondirectory_custom:/assets/fusiondirectory
    # - fusiondirectory_plugins-custom:/assets/plugins-custom
    environment:
    - VIRTUAL_HOST=fusiondirectory.example.org
    - VIRTUAL_NETWORK=web
    - VIRTUAL_PORT=80
    # - LETSENCRYPT_HOST=fusiondirectory.example.org
    # - LETSENCRYPT_EMAIL=yourname@example.org

    - CONTAINER_NAME=fusiondirectory

    # Upstream default, and default enabled on docker-openldap-fusiondirectory
    # https://github.com/tiredofit/docker-openldap-fusiondirectory/tree/2.6-1.4#schema-installation
    - ENABLE_ARGONAUT=FALSE
    - PLUGIN_AUDIT=TRUE
    - PLUGIN_DNS=TRUE
    - PLUGIN_DSA=TRUE
    - PLUGIN_LDAPDUMP=TRUE
    - PLUGIN_LDAPMANAGER=TRUE
    - PLUGIN_MAIL=TRUE
    - PLUGIN_PERSONAL=TRUE
    - PLUGIN_PPOLICY=TRUE
    - PLUGIN_SSH=TRUE
    - PLUGIN_SYSTEMS=TRUE
    - PLUGIN_WEBSERVICE=TRUE
    # Custom
    - PLUGIN_MIXEDGROUPS=TRUE # Seems to be needed for OpenLDAP SCHEMA_TYPE=rfc2307bis
    - PLUGIN_ALIAS=TRUE
    - PLUGIN_APPLICATIONS=TRUE
    - PLUGIN_ARCHIVE=TRUE
    - PLUGIN_CERTIFICATES=TRUE
    - PLUGIN_COMMUNITY=TRUE
    - PLUGIN_DOVECOT=TRUE
    - PLUGIN_DYNGROUPS=TRUE
    - PLUGIN_GPG=TRUE
    - PLUGIN_POSIX=TRUE
    - PLUGIN_POSTFIX=TRUE
    - PLUGIN_QUOTA
    - PLUGIN_SPAMASSASSIN
    - PLUGIN_SUDO
    - PLUGIN_WEBLINK=TRUE

    - LDAP1_HOST=openldap
    - LDAP1_BASE_DN=dc=example,dc=org
    - LDAP1_ADMIN_DN=cn=admin,dc=example,dc=org
    - LDAP1_ADMIN_PASS=admin
    - LDAP1_PORT=389
    - LDAP1_NAME=Production

    #- LDAP2_BASE_DN=dc=example,dc=org
    #- LDAP2_ADMIN_DN=cn=admin,dc=example,dc=org
    #- LDAP2_HOST=openldap-fusiondirectory2
    #- LDAP2_ADMIN_PASS=password2
    #- LDAP2_NAME=Development
    #- LDAP2_TLS=TRUE
    networks:
    - web
    - openldap
    expose:
      - 80
    restart: always

networks:
  web:
    external: true
  openldap:
    external: true

volumes:
  fusiondirectory_logs:
    driver_opts:
      type: none
      device: ${VOLUMES_ROOT}/logs
      o: bind
  # fusiondirectory_custom:
  #   driver_opts:
  #     type: none
  #     device: ${VOLUMES_ROOT}/custom
  #     o: bind
  # fusiondirectory_plugins-custom:
  #   driver_opts:
  #     type: none
  #     device: ${VOLUMES_ROOT}/plugins-custom
  #     o: bind
